### ISSUE TITLE
Game becomes unstable if you dismiss then return to it

### ISSUE THREAD

**Issue by asimihsan** [asimihsan/dualnback#4]
Scenario is:
- Run the game, it's working fine.
- Press the HOME button to dismiss it.
- Return to the game by selecting its icon.
- Several unexpected things occur:
  - The "Current Intervals" message box appears twice, I only expect it once.
  - Sometimes you cannot hear sounds coming out from the game.

I'm putting the low-level logs here. It includes an error stack trace, which I haven't understood yet. This is the log output when you've just clicked on the application to restore it back to the foreground.

```
05-12 20:19:18.172: V/PhoneWindow(2805): DecorView setVisiblity: visibility = 0
05-12 20:19:18.189: D/GameActivityHandler::handleMessage()(2805): MSG_TYPE_CREATE
05-12 20:19:18.198: V/InputMethodManager(2805): onWindowFocus: null softInputMode=288 first=true flags=#8010100
05-12 20:19:18.198: V/InputMethodManager(2805): START INPUT: com.android.internal.policy.impl.PhoneWindow$DecorView{4123d028 V.E..... R.....ID 0,0-320,533} ic=null tba=android.view.inputmethod.EditorInfo@412edf10 controlFlags=#104
05-12 20:19:18.201: V/InputMethodManager(2805): Starting input: Bind result=InputBindResult{com.android.internal.view.IInputMethodSession$Stub$Proxy@412ee860 com.android.inputmethod.latin/.LatinIME #35}
05-12 20:19:18.222: D/DrawView::draw()(2805): entry
05-12 20:19:18.230: D/GameActivityHandler::handleMessage()(2805): MSG_TYPE_INITIALIZE
05-12 20:19:18.344: D/GameActivityHandler::handleMessage()(2805): MSG_TYPE_INITIALIZE
05-12 20:19:18.344: I/InputMethodManager(2805): handleMessage: MSG_SET_ACTIVE true, was false
05-12 20:19:18.344: D/Handler::handleMessage()(2805): MSG_TYPE_DRAWING_DONE. mActivityState: 1
05-12 20:19:18.344: D/GameActivityHandler::handleMessage()(2805): MSG_TYPE_INITIALIZE_DONE
05-12 20:19:18.345: D/GameActivity::setmAlertDialog()(2805): entry. mAlertDialog: null, alert: android.app.AlertDialog@412f2640
05-12 20:19:18.368: D/GameActivity::getmAlertDialog()(2805): entry. mAlertDialog: android.app.AlertDialog@412f2640
05-12 20:19:18.368: D/GameActivity::getmAlertDialog()(2805): activity: com.gyrovague.dualnback.GameActivity@4123a2e8
05-12 20:19:18.368: D/GameActivityHandler::handleMessage()(2805): MSG_TYPE_INITIALIZE_DONE
05-12 20:19:18.370: D/GameActivity::setmAlertDialog()(2805): entry. mAlertDialog: android.app.AlertDialog@412f2640, alert: android.app.AlertDialog@412fcae8
05-12 20:19:18.398: D/GameActivity::getmAlertDialog()(2805): entry. mAlertDialog: android.app.AlertDialog@412fcae8
05-12 20:19:18.398: D/GameActivity::getmAlertDialog()(2805): activity: com.gyrovague.dualnback.GameActivity@4123a2e8
05-12 20:19:18.565: D/DrawView::draw()(2805): entry
05-12 20:19:18.566: D/Handler::handleMessage()(2805): MSG_TYPE_DRAWING_DONE. mActivityState: 10
05-12 20:19:19.624: I/SurfaceTextureClient(2805): [STC::queueBuffer] (this:0x51b319e0) fps:1.74, dur:1147.57, max:1082.25, min:65.32
05-12 20:19:19.694: I/SurfaceTextureClient(2805): [STC::queueBuffer] (this:0x51b0f578) fps:0.83, dur:1200.21, max:1200.21, min:1200.21
05-12 20:19:20.714: I/SurfaceTextureClient(2805): [STC::queueBuffer] (this:0x51b0f578) fps:8.82, dur:1019.89, max:778.28, min:25.64
05-12 20:19:20.786: V/Provider/Settings(2805): invalidate [system]: current 2 != cached 0
05-12 20:19:20.790: D/ActivityThread(2805): installProvider: context=android.app.ContextImpl@4123a8d0holder=android.app.IActivityManager$ContentProviderHolder@413098d0noisy=truenoReleaseNeeded=truestable=true
05-12 20:19:20.793: V/Provider/Settings(2805): from db cache, name = sound_effects_enabled , value = 1
05-12 20:19:20.811: D/GameActivityHandler::handleMessage()(2805): MSG_TYPE_NEW_TRIAL. mActivityState: 10
05-12 20:19:21.311: D/GameActivityHandler::handleMessage()(2805): current block not finished
05-12 20:19:21.345: D/DrawView::draw()(2805): entry
05-12 20:19:21.347: I/SurfaceTextureClient(2805): [STC::queueBuffer] (this:0x51af6dc0) fps:0.64, dur:3123.37, max:2780.60, min:342.78
05-12 20:19:21.349: D/Handler::handleMessage()(2805): MSG_TYPE_DRAWING_DONE. mActivityState: 6
05-12 20:19:21.350: D/MediaPlayer(2805): Don't notify duration to com.gyrovague.dualnback!
05-12 20:19:21.423: I/SurfaceTextureClient(2805): [STC::queueBuffer] (this:0x51b319e0) fps:5.56, dur:1798.58, max:1518.20, min:29.49
05-12 20:19:21.931: D/DrawView::draw()(2805): entry
05-12 20:19:21.933: D/Handler::handleMessage()(2805): MSG_TYPE_DRAWING_DONE. mActivityState: 7
05-12 20:19:22.116: V/Provider/Settings(2805):  from settings cache , name = sound_effects_enabled , value = 1
05-12 20:19:22.152: D/GameActivityHandler::handleMessage()(2805): MSG_TYPE_NEW_TRIAL. mActivityState: 7
05-12 20:19:22.652: D/GameActivityHandler::handleMessage()(2805): current block not finished
05-12 20:19:22.682: D/DrawView::draw()(2805): entry
05-12 20:19:22.685: I/SurfaceTextureClient(2805): [STC::queueBuffer] (this:0x51af6dc0) fps:1.49, dur:1338.19, max:752.28, min:585.92
05-12 20:19:22.688: V/InputMethodManager(2805): onWindowFocus: null softInputMode=32 first=false flags=#8010100
05-12 20:19:22.690: D/Handler::handleMessage()(2805): MSG_TYPE_DRAWING_DONE. mActivityState: 6
05-12 20:19:22.691: E/MediaPlayer(2805): prepareAsync called in state 128
05-12 20:19:22.692: W/System.err(2805): java.lang.IllegalStateException
05-12 20:19:22.694: W/System.err(2805):     at android.media.MediaPlayer.prepare(Native Method)
05-12 20:19:22.694: W/System.err(2805):     at com.gyrovague.dualnback.SoundManager.playSound(SoundManager.java:209)
05-12 20:19:22.694: W/System.err(2805):     at com.gyrovague.dualnback.GameActivity$1.handleMessage(GameActivity.java:235)
05-12 20:19:22.694: W/System.err(2805):     at android.os.Handler.dispatchMessage(Handler.java:107)
05-12 20:19:22.695: W/System.err(2805):     at android.os.Looper.loop(Looper.java:194)
05-12 20:19:22.695: W/System.err(2805):     at android.app.ActivityThread.main(ActivityThread.java:5371)
05-12 20:19:22.695: W/System.err(2805):     at java.lang.reflect.Method.invokeNative(Native Method)
05-12 20:19:22.696: W/System.err(2805):     at java.lang.reflect.Method.invoke(Method.java:525)
05-12 20:19:22.696: W/System.err(2805):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
05-12 20:19:22.696: W/System.err(2805):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
05-12 20:19:22.696: W/System.err(2805):     at dalvik.system.NativeStart.main(Native Method)
05-12 20:19:22.729: D/DrawView::draw()(2805): entry
05-12 20:19:22.731: D/Handler::handleMessage()(2805): MSG_TYPE_DRAWING_DONE. mActivityState: 7
05-12 20:19:23.243: D/DrawView::draw()(2805): entry
05-12 20:19:23.244: D/Handler::handleMessage()(2805): MSG_TYPE_DRAWING_DONE. mActivityState: 7
05-12 20:19:25.720: D/Handler::handleMessage()(2805): MSG_TYPE_GUESS_ 4, mActivityState: 7
05-12 20:19:25.720: D/Handler::handleMessage()(2805): Accept guess.
05-12 20:19:25.720: D/Main::validateGuess()(2805): entry
05-12 20:19:25.720: D/Main::disableAll()(2805): entry
05-12 20:19:25.722: D/Main::resetButtonsFeedback()(2805): entry
05-12 20:19:25.723: D/GameManager::evaluateGuess()(2805): entry.  guess: 0
05-12 20:19:25.724: D/GameManager::evaluateGuess()(2805): mCurrentTrial: 0, mNInterval: 2, guessable: false
05-12 20:19:25.724: D/GameActivity::validateGuess(2805): is_correct: true
05-12 20:19:25.744: D/DrawView::draw()(2805): entry
05-12 20:19:25.745: I/SurfaceTextureClient(2805): [STC::queueBuffer] (this:0x51af6dc0) fps:0.98, dur:3060.68, max:2501.40, min:45.61
05-12 20:19:25.748: D/GameActivityHandler::handleMessage()(2805): MSG_TYPE_NEW_TRIAL. mActivityState: 5
05-12 20:19:26.249: D/GameActivityHandler::handleMessage()(2805): current block not finished
05-12 20:19:26.250: D/Handler::handleMessage()(2805): MSG_TYPE_DRAWING_DONE. mActivityState: 6
05-12 20:19:26.251: D/MediaPlayer(2805): Don't notify duration to com.gyrovague.dualnback!
05-12 20:19:26.309: D/DrawView::draw()(2805): entry
05-12 20:19:26.311: D/Handler::handleMessage()(2805): MSG_TYPE_DRAWING_DONE. mActivityState: 7
```

This bug has existed before @xantares pull requests, it's a long-standing issue.

**Comment by asimihsan** [comment]
The best next question to answer is "why does the alert dialog appear twice?". Although I'm not sure yet we are probably not destroying the game properly when it goes into the background, and then when it resumes we're re-initializing on top of itself.

It's important to destroy everything in `onPause()`, and then recreate everything in `onResume()`. For more information on the Android lifecycle see:

http://developer.android.com/training/basics/activity-lifecycle/pausing.html

http://developer.android.com/training/basics/activity-lifecycle/stopping.html

**Comment by asimihsan** [comment]
To be clear I opened this issue for myself to fix.
